"""
main.py
=======
FastAPI backend for the AI-Assisted Breast Cancer Diagnosis Support System.

Serves predictions from a trained scikit-learn model (see /model/train_model.py)
over a REST API consumed by the frontend in /frontend/index.html.

Run:
    uvicorn main:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI/OpenAPI) are then available at:
    http://localhost:8000/docs
"""

import json
from pathlib import Path

import joblib
import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from schemas import CellFeatures, PredictionResponse, ModelInfoResponse, HealthResponse

BASE_DIR = Path(__file__).parent
MODEL_DIR = BASE_DIR.parent / "model" / "saved_models"

app = FastAPI(
    title="Breast Cancer Diagnosis Support API",
    description=(
        "Predicts malignant vs. benign classification from digitized fine-needle "
        "aspirate (FNA) cell nuclei measurements. Intended as a clinical decision-support "
        "aid, not a replacement for professional diagnosis."
    ),
    version="1.0.0",
)

# Allow the static frontend (served from file:// or a different port) to call this API.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Load model artifacts once at startup
# ---------------------------------------------------------------------------
model = None
scaler = None
metadata = None


@app.on_event("startup")
def load_artifacts():
    global model, scaler, metadata
    model = joblib.load(MODEL_DIR / "best_model.joblib")
    scaler = joblib.load(MODEL_DIR / "scaler.joblib")
    with open(MODEL_DIR / "model_metadata.json") as f:
        metadata = json.load(f)
    print(f"Loaded model: {metadata['model_name']}")


def _risk_level(malignant_prob: float) -> str:
    if malignant_prob < 0.2:
        return "Low"
    elif malignant_prob < 0.6:
        return "Moderate"
    return "High"


@app.get("/", response_model=HealthResponse, tags=["Health"])
def root():
    """Basic health check."""
    return HealthResponse(status="ok", model_loaded=model is not None)


@app.get("/health", response_model=HealthResponse, tags=["Health"])
def health():
    """Health check used by monitoring / uptime probes."""
    return HealthResponse(status="ok", model_loaded=model is not None)


@app.get("/model-info", response_model=ModelInfoResponse, tags=["Model"])
def model_info():
    """
    Returns metadata about the currently loaded model: which algorithm was
    selected, how it performed on the held-out test set, and the exact
    feature order it expects.
    """
    if metadata is None:
        raise HTTPException(status_code=503, detail="Model metadata not loaded")
    return ModelInfoResponse(
        model_name=metadata["model_name"],
        n_train_samples=metadata["n_train_samples"],
        n_test_samples=metadata["n_test_samples"],
        test_metrics=metadata["test_metrics"],
        malignant_class_recall=metadata["malignant_class_recall"],
        feature_order=metadata["feature_order"],
    )


@app.post("/predict", response_model=PredictionResponse, tags=["Prediction"])
def predict(features: CellFeatures):
    """
    Predict malignant vs. benign from 30 cell-nuclei measurements.

    Input fields map 1:1 to the WDBC feature set (mean / error / worst value
    for each of 10 base measurements). See the request schema example in
    /docs for realistic sample values.
    """
    if model is None or scaler is None:
        raise HTTPException(status_code=503, detail="Model not loaded yet, try again shortly")

    # Reconstruct the exact column order the model was trained on
    ordered = [
        features.mean_radius, features.mean_texture, features.mean_perimeter,
        features.mean_area, features.mean_smoothness, features.mean_compactness,
        features.mean_concavity, features.mean_concave_points, features.mean_symmetry,
        features.mean_fractal_dimension,
        features.radius_error, features.texture_error, features.perimeter_error,
        features.area_error, features.smoothness_error, features.compactness_error,
        features.concavity_error, features.concave_points_error, features.symmetry_error,
        features.fractal_dimension_error,
        features.worst_radius, features.worst_texture, features.worst_perimeter,
        features.worst_area, features.worst_smoothness, features.worst_compactness,
        features.worst_concavity, features.worst_concave_points, features.worst_symmetry,
        features.worst_fractal_dimension,
    ]

    X = np.array(ordered).reshape(1, -1)
    X_scaled = scaler.transform(X)

    proba = model.predict_proba(X_scaled)[0]  # [P(malignant=0), P(benign=1)]
    malignant_prob = float(proba[0])
    benign_prob = float(proba[1])

    diagnosis = "malignant" if malignant_prob > benign_prob else "benign"
    confidence = max(malignant_prob, benign_prob)

    return PredictionResponse(
        diagnosis=diagnosis,
        malignant_probability=round(malignant_prob, 4),
        benign_probability=round(benign_prob, 4),
        risk_level=_risk_level(malignant_prob),
        confidence=round(confidence, 4),
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
